### ISSUE TITLE
Looks like color stack is being retained.

### ISSUE THREAD

**Issue by doowb** [doowb/ansi-colors#15]
I believe there's a regression in #13, which appears to be related to the color stack not being cleared.

@jonschlinkert this might be the issue you mentioned to me when we received this PR.

**Comment by jonschlinkert** [comment]
I haven't had a chance to do a proper code review of @lukeed's changes, but if I recall correctly this is why a new function was created in the stack.

**Comment by jonschlinkert** [comment]
> It's a different approach to handling the functions & the keys stack. I'm not sure if it solves this bug, but I think it should.

What do you think the two bugs are specifically? And why do you think they are happening?

**Comment by lukeed** [comment]
I'm not aware of your second bug, unless it has to do with the `hasOpen` and `hasClose` bits. Have still not seen a need for that personally.

For this issue, the main for loop just traverses the stack when instead it should be manipulating the length as it chugs along. Same function is reused due to the singular binding, so previous stack remains. Don't want to post code now as I know both projects are being closely watched by prying eyes.

**Comment by jonschlinkert** [comment]
> Don't want to post code now as I know both projects are being closely watched by prying eyes.

To be clear, we knew your code had bugs before your PR. We merged your PR both as a show of good faith and also because we knew that if you didn't deprecate kleur as you said you would during our discussion, we could just point out this issue in the future when we replace your library in every project that uses it. After all, you only made two actual code changes to the code you copied from this library, and both of those changes result in bugs.

**Comment by doowb** [comment]
Fixed in version 2.0.4

**Comment by jonschlinkert** [comment]
Believe it or not, I just found a third bug from the PR.
