### ISSUE TITLE
Render bug in bound methods

### ISSUE THREAD

**Issue by jorgebucaran** [doowb/ansi-colors#18]
The following example has an unexpected render bug.

```js
const { red } = require("ansi-colors")

const boundRedBold = red.bold

console.log(
  red.blue.bold("Blue Bold"),
  boundRedBold("Red Bold") 
)
```

<img width="621" alt="screen shot 2018-08-23 at 11 29 27" src="https://user-images.githubusercontent.com/56996/44501353-efff7880-a6c7-11e8-8809-e5bd52b2a922.png">

It seems `boundRedBold`'s internal stack should not be jumbled up as a result of calling `red.blue.bold()`.

**Comment by jonschlinkert** [comment]
Thanks for the detective work on this! I completely forgot about this other binding case. (and thanks for the dialog about these libs)

**Solution**

To prevent this color-switch from happening, we need to create a new function _inside the getter_ with its own stack (so that the function's stack is not updated in future calls to that color - since new calls to the color will be an entirely new function). This also means we'll need to set the prototype of that new function to the styles object _inside the getter_, which will be slower, but it's necessary. This is what we did in a previous version of ansi-colors and I forgot about this case and changed the code so that `.setPrototypeOf` was called outside of the getter to make it more performant (turbocolor and kleur also have this bug, since they do something similar). 

I'll push up an update today. Thanks again!

**Comment by jorgebucaran** [comment]
> This also means we'll need to set the prototype of that new function to the styles object inside the getter, which will be slower, but it's necessary.

Yes, that's what I thought. Thanks! 👋

**Comment by jonschlinkert** [comment]
should be fixed. thanks again.
