### ISSUE TITLE
enabled is const and cannot be assigned.

### ISSUE THREAD

**Issue by Weishi93** [doowb/ansi-colors#29]
Try to disable color mode in my Typescript code.
`import * as colors from "ansi-colors";
colors.enabled = false;
`
It pops up this error
`[ts] Cannot assign to 'enabled' because it is a constant or a read-only property.`

**Comment by doowb** [comment]
Is that because TypeScript is seeing [this definition](https://github.com/doowb/ansi-colors/blob/master/types/index.d.ts#L136)?

If so, could you try removing the `const` to see if that works? Would you also be able to do a PR to update any other types that should be able to be set?

Thanks for finding this and opening an issue.

**Comment by jonschlinkert** [comment]
> Is that because TypeScript is seeing [this definition](https://github.com/doowb/ansi-colors/blob/master/types/index.d.ts#L136)?

@doowb it's not typescript, I'm to blame on this one. I used `const = { enabled: true }` in the code. We just need to push up a patch.

**Comment by Weishi93** [comment]
Yes, I think that's because TS checks `index.d.ts` file under `types` folder and found `enabled` is const.
Will submit PR after work.

**Comment by anodynos** [comment]
For some odd reason I'm still having this problem with latest version. I can see the variable being `export let ...` and not const, I don't know why TS 4.9.5 doesnt like. Anyway, `@ts-ignore` to the rescue!
